name: main team accept pull request

on:
  pull_request:
    branches: ['Main_team']
env:
    PR_NUMBER: ${{ github.event.number }}
    
jobs:
  recive_merge:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:   
    - name: Merge Pull Request
      uses: juliangruber/approve-pull-request-action@v2.0.0
     
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        number: ${{ env.PR_NUMBER }}
        method: squash # merge rebase
        repo: chickiyeah/green_kiosk

    - name: Merge Pull Request
      uses: juliangruber/merge-pull-request-action@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        number: ${{ env.PR_NUMBER }}
        method: squash # merge rebase
        repo: chickiyeah/green_kiosk

